### PR TITLE
fix: Added an aria label to the list box, resolves #1192.

### LINKED ISSUE #1192: MultiSelect: Accessibility failure due to widget name
When using the MultiSelect component, we're seeing the following error in DAP that's causing our accessibility tests to fail:

image

After version `6.18.4` was released last Monday we were passing all of our accessibility tests with the same usage of MultiSelect, and since then this error has surfaced. We're currently on version `6.20.0`.

### PR DESCRIPTION
**Pull request by zgrossbart**
Closes #1192

This change adds a default aria label to list boxes so we can pass the DAP tests.

This change also adds that new aria label to unit tests.

### CODE REVIEW

File: src/components/ListBox/ListBox.js [hunk 1]
```diff
@@ -82,12 +84,18 @@ ListBox.propTypes = {
...
+   * Specify the "aria-label" of the ListBox.
+   */
+  ariaLabel: PropTypes.string,
 };
 
 ListBox.defaultProps = {
   innerRef: () => {},
   disabled: false,
   type: 'default',
+  ariaLabel: 'ListBox',
```
Comment (joshblack) [inline src/components/ListBox/ListBox.js]: Should we have a default value for this, or just leave it blank?

Comment (zgrossbart) [reply src/components/ListBox/ListBox.js]: Having a default value here doesn't hurt anything and it will help users that are using screen readers.

Comment (zgrossbart) [reply src/components/ListBox/ListBox.js]: It's also worth noting that many other Carbon components have a default value for the aria-label.

Comment (joshblack) [reply src/components/ListBox/ListBox.js]: @zgrossbart totally understand, it might help if the label itself is more descriptive then if the intent is to aid the user here by default. List Box is something that could cause confusion as that term is not very common, or at least that's my assumption.

Comment (zgrossbart) [reply src/components/ListBox/ListBox.js]: I based the defaults on the other defaults which were very simple.  Just identifying what the element was.  I'm happy to change it.  Do you have another suggestion?

Comment (joshblack) [reply src/components/ListBox/ListBox.js]: How about "Choose an item" or "Choose an option"? Just basing off of: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

Comment (zgrossbart) [reply src/components/ListBox/ListBox.js]: Sounds good to me.
