### PR TITLE
fix(notification): adds aria-label to button

### LINKED ISSUE #2246: AVT 1 - Toast Notification: DAP violation the form control is missing an associated
## Environment
macOS Mojave version 10.14.2
Chrome version 72.0.3626.96 (Official Build) (64-bit)

## Detailed Description
Run DAP with Feb. 2019 ruleset on the Expandable Tile component
See screenshot below for violation:
Screen Shot 2019-04-19 at 8 50 44 AM

### PR DESCRIPTION
**Pull request by dakahn**
closes #2246 

adds aria-label to close button on toast notification so that the button's purpose can be known to screen reader users.

#### Changelog

- adds `aria-label={iconDescription}` to the `<button>` component

### CODE REVIEW

File: src/components/Notification/Notification.js [hunk 1]
```diff
@@ -664,6 +665,7 @@ class Notification extends Component {
         className={notificationClasses.toast}>
         <NotificationTextDetails
           title={title}
+          aria-label="catcatcat"
```
Comment (asudoh) [inline src/components/Notification/Notification.js]: Did you mean to use an existing prop or introduce a prop here?

Comment (dakahn) [reply src/components/Notification/Notification.js]: 🤦‍♂️ Ugh, my bad. That was from testing. Will remove.
