### PR TITLE
fix(components): avoid being shown as ForwardRef

### LINKED ISSUE #1786: Checkbox: Shown as ForwardRef in React DevTools
## Detailed description

> Describe in detail the issue you're having.

React DevTools shows our `<Checkbox>` as `<ForwardRef>`:

image

> Is this issue related to a specific component?

`<Checkbox>`, `<Select>` and `<TextInput>`

> What did you expect to happen? What happened instead? What would you like to see changed?

React DevTools shows our `<Checkbox>` as it is.

> What version of the Carbon Design System are you using?

`6.79.0`

### LINKED ISSUE #1789: TextInput is shown as ForwardRef in React dev tool
image

If this is permanent please close and let me know. Much prefer TextInput though ;)

See comment from me in: https://github.com/IBM/carbon-components-react/issues/1786

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #1786.
Fixes #1789.

#### Changelog

**New**

- Added `displayName` to components with `React.forwardRef()`.

### CODE REVIEW

File: src/components/Checkbox/Checkbox.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ import { settings } from 'carbon-components';
 
 const { prefix } = settings;
 
-const Checkbox = ({
+const CheckboxImpl = ({
```
Comment (asudoh) [inline src/components/Checkbox/Checkbox.js]: Though merging `Checkbox` and `CheckboxImpl` prevents `<Checkbox><CheckboxImpl ... /><Checkbox>` being shown in React DevTools, such technique cannot be applied to stateful components, and thus I kept it intact.

**Comment by rmullan** [comment]
Thank you :)

File: src/components/Checkbox/Checkbox.js (hunk 1 above)
Comment (emyarod) [reply src/components/Checkbox/Checkbox.js]: would this be a reason not to convert `<Checkbox>` to a stateful component? I saw that you suggested that as a possible alternative solution to set indeterminate prop when a ref is also passed into `<Checkbox>`

**Comment by joshblack** [comment]
Is this so that `Checkbox` retains its displayName? Would we be okay with `ForwardRef(Checkbox)` as well?

File: src/components/Checkbox/Checkbox.js (hunk 1 above)
Comment (asudoh) [reply src/components/Checkbox/Checkbox.js]: @emyarod Agreed that `<...Impl>` showing up in React DevTools (and other env) is noisy, but seems that we cannot avoid that e.g. for `<NumberInput>`, which is stateful. I think this shouldn't stop us from moving `<Checkbox>` to stateful if we think we need it.

**Comment by asudoh** [comment]
@joshblack `ForwardRef(Checkbox)` is fine to me, though I think just `Checkbox` being shown is better.

File: src/components/Checkbox/Checkbox.js (hunk 1 above)
Comment (asudoh) [reply src/components/Checkbox/Checkbox.js]: Talked to @emyarod offline, he seems fine with `ForwardRef(Checkbox)` though he seems to prefer the other. I went ahead with `ForwardRef(Checkbox)` based on that.

**Comment by silesky** [comment]
@asudoh This works fine, but might be worth refactoring into a HoC to avoid the boilerplate, like in this stackoverflow

https://stackoverflow.com/a/53875195/6216756

File: src/components/Checkbox/Checkbox.js [hunk 2]
```diff
@@ -126,6 +126,8 @@ Checkbox.defaultProps = {
   indeterminate: false,
 };
 
-export default React.forwardRef((props, ref) => (
-  <Checkbox {...props} forwardRef={ref} />
-));
+export default React.forwardRef(
+  Object.assign((props, ref) => <Checkbox {...props} forwardRef={ref} />, {
+    displayName: 'Checkbox',
```
Comment (silesky) [inline src/components/Checkbox/Checkbox.js]: this displayName may be problematic, because from my understanding this means component tree will end up looking like
```
<Checkbox>
  <Checkbox />
<Checkbox>
```
this could break a lot of unit tests that do something like Wrapper.find('Checkbox') because suddenly there are two checkboxes, instead of one

it's better to have something like
<withForwardedRef(Checkbox)>
 <Checkbox>
</withForwardedRef(Checkbox)>

**Comment by joshblack** [comment]
Oh duh, it's the function name passed to `React.forwardRef` 🤦‍♂️ 

Would it be helpful to separate out the function passed to it and set the `displayName` manually then?

```jsx
const Checkbox = () => {
  // ...
};

function forwardRef(props, ref) {
  return <Checkbox {...props} innerRef={ref} />;
}

forwardRef.displayName = 'Checkbox';

export default React.forwardRef(forwardRef);
```

File: src/components/Checkbox/Checkbox.js [hunk 3]
```diff
@@ -126,6 +126,8 @@ Checkbox.defaultProps = {
...
 };
 
-export default React.forwardRef((props, ref) => (
-  <Checkbox {...props} forwardRef={ref} />
-));
+const forwardRef = (props, ref) => <Checkbox {...props} forwardRef={ref} />;
+
+forwardRef.displayName = 'Checkbox';
+
+export default forwardRef;
```
Comment (joshblack) [inline src/components/Checkbox/Checkbox.js]: Might need to be:

```suggestion
export default React.forwardRef(forwardRef);
```

?

Comment (asudoh) [reply src/components/Checkbox/Checkbox.js]: Oops you are right - Made changes as such.

**Comment by asudoh** [comment]
@joshblack Did you have any further comments/thoughts...? Thanks!

**Comment by asudoh** [comment]
Merging in as all comments from the reviewers have been addressed - Anybody don't hesitate to speak up otherwise - Thanks! (Note to @silesky - I see reducing the boilerplate definitely is an interesting idea and we'll take note)
